# Generated by Django 5.0.1 on 2024-05-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=40, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('idPlanta', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Planta')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio'))
            ],
        ),
    ]
